name: Build Lens

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths-ignore:
      - "**/README.md"
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 360
    steps:
      - name: Checkout OpenLens
        uses: actions/checkout@v3
      - name: Export version to variable
        run: |
          export LENS_VERSION=$(cat version)
          echo "LENS_VERSION=$LENS_VERSION" >> $GITHUB_ENV
        shell: bash
      - uses: actions/setup-node@v3
        with:
          node-version: 16.19.0
      - name: Checkout Upstream Lens
        uses: actions/checkout@v3
        with:
          repository: lensapp/lens
          path: lens
          ref: v${{ env.LENS_VERSION }}
          fetch-depth: 1
      - name: Patch Upstream Lens
        run: |
          node update.js
      - name: Build Lens
        run: |
          mkdir releasefiles
          if [ "$RUNNER_OS" == "Windows" ]; then
            choco install visualstudio2019buildtools visualstudio2019-workload-vctools
          fi
          if [ "$RUNNER_OS" == "macOS" ]; then
            if [ "${CSC_LINK}" = "" ]; then
              unset CSC_LINK
            fi
            
            if [ "${CSC_KEY_PASSWORD}" = "" ]; then
              unset CSC_KEY_PASSWORD
            fi
            yarn
            yarn run build
            yarn run build:app
            for file in packages/open-lens/dist/OpenLens-${{ env.LENS_VERSION }}.dmg; do
              if [[ "$file" == *"arm64"* ]]; then
                cp "$file" releasefiles/OpenLens-${{ env.LENS_VERSION }}-arm64.dmg
              else
                cp "$file" releasefiles/OpenLens-${{ env.LENS_VERSION }}.dmg
              fi
            done
            for file in packages/open-lens/dist/OpenLens-${{ env.LENS_VERSION }}-mac.zip; do
              if [[ "$file" == *"arm64"* ]]; then
                cp "$file" releasefiles/OpenLens-${{ env.LENS_VERSION }}-arm64.zip
              else
                cp "$file" releasefiles/OpenLens-${{ env.LENS_VERSION }}.zip
              fi
            done
          elif [ "$RUNNER_OS" == "Linux" ]; then
            yarn
            yarn run build
            yarn run build:app
            cp packages/open-lens/dist/OpenLens-${{ env.LENS_VERSION }}.x86_64.AppImage releasefiles/OpenLens-${{ env.LENS_VERSION }}.AppImage
            cp packages/open-lens/dist/OpenLens-${{ env.LENS_VERSION }}.amd64.deb releasefiles/OpenLens-${{ env.LENS_VERSION }}.deb
            cp packages/open-lens/dist/OpenLens-${{ env.LENS_VERSION }}.x86_64.rpm releasefiles/OpenLens-${{ env.LENS_VERSION }}.rpm
            cp packages/open-lens/dist/OpenLens-${{ env.LENS_VERSION }}.arm64.AppImage releasefiles/OpenLens-${{ env.LENS_VERSION }}.arm64.AppImage
            cp packages/open-lens/dist/OpenLens-${{ env.LENS_VERSION }}.arm64.deb releasefiles/OpenLens-${{ env.LENS_VERSION }}.arm64.deb
            cp packages/open-lens/dist/OpenLens-${{ env.LENS_VERSION }}.aarch64.rpm releasefiles/OpenLens-${{ env.LENS_VERSION }}.arm64.rpm
          else
            yarn
            yarn run build
            yarn run build:app
            cp packages/open-lens/dist/OpenLens*.exe releasefiles/OpenLens-${{ env.LENS_VERSION }}.exe
            cp packages/open-lens/dist/OpenLens*.exe packages/open-lens/dist/OpenLens-${{ env.LENS_VERSION }}.exe
          fi
        shell: bash
        working-directory: lens
        env:
          APPBUNDLEID: "io.kontena.lens-app"
          APPLEID: ${{ secrets.APPLEID }}
          APPLEIDPASS: ${{ secrets.APPLEIDPASS }}

      - name: Calculate SHA256 checksum
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            certutil -hashfile OpenLens-${{ env.LENS_VERSION }}.exe SHA256 | tee OpenLens-${{ env.LENS_VERSION }}.exe.sha256
          else
            for filename in OpenLens-${{ env.LENS_VERSION }}*; do shasum -a 256 ${filename} | tee ${filename}.sha256 ; done
          fi
        shell: bash
        working-directory: lens/packages/open-lens/dist

      - uses: actions/upload-artifact@v3
        if: github.ref != 'refs/heads/main'
        with:
          name: OpenLens-${{ matrix.os }}
          retention-days: 5
          path: |
            lens/packages/open-lens/dist/OpenLens-${{ env.LENS_VERSION }}*.dmg
            lens/packages/open-lens/dist/OpenLens-${{ env.LENS_VERSION }}*.AppImage
            lens/packages/open-lens/dist/OpenLens-${{ env.LENS_VERSION }}*.deb
            lens/packages/open-lens/dist/OpenLens-${{ env.LENS_VERSION }}*.rpm
            lens/packages/open-lens/dist/OpenLens-${{ env.LENS_VERSION }}*.zip
            lens/packages/open-lens/dist/OpenLens-${{ env.LENS_VERSION }}.exe
            lens/packages/open-lens/dist/OpenLens-${{ env.LENS_VERSION }}*.sha256

      - name: Generate Changelog
        run: curl -s https://api.github.com/repos/lensapp/lens/releases/latest | jq -r 'select(.prerelease == false) | .body[0:]' > ${{ github.workspace }}-CHANGELOG.txt
      - name: Release
        uses: softprops/action-gh-release@v0.1.15
        if: github.ref == 'refs/heads/main'
        with:
          tag_name: v${{ env.LENS_VERSION }}
          body_path: ${{ github.workspace }}-CHANGELOG.txt
          files: |
            lens/packages/open-lens/dist/OpenLens-${{ env.LENS_VERSION }}*.dmg
            lens/packages/open-lens/dist/OpenLens-${{ env.LENS_VERSION }}*.AppImage
            lens/packages/open-lens/dist/OpenLens-${{ env.LENS_VERSION }}*.deb
            lens/packages/open-lens/dist/OpenLens-${{ env.LENS_VERSION }}*.rpm
            lens/packages/open-lens/dist/OpenLens-${{ env.LENS_VERSION }}*.zip
            lens/packages/open-lens/dist/OpenLens-${{ env.LENS_VERSION }}.exe
            lens/packages/open-lens/dist/OpenLens-${{ env.LENS_VERSION }}*.sha256
      - name: Latest
        uses: softprops/action-gh-release@v0.1.15
        if: github.ref == 'refs/heads/main'
        with:
          tag_name: Latest
          files: |
            lens/packages/open-lens/dist/OpenLens-${{ env.LENS_VERSION }}*.dmg
            lens/packages/open-lens/dist/OpenLens-${{ env.LENS_VERSION }}*.AppImage
            lens/packages/open-lens/dist/OpenLens-${{ env.LENS_VERSION }}*.deb
            lens/packages/open-lens/dist/OpenLens-${{ env.LENS_VERSION }}*.rpm
            lens/packages/open-lens/dist/OpenLens-${{ env.LENS_VERSION }}*.zip
            lens/packages/open-lens/dist/OpenLens.Setup.${{ env.LENS_VERSION }}.exe
            lens/packages/open-lens/dist/lates*.yml
